server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: users-service-route
          uri: lb://USERS-SERVICE
          predicates:
            - Path=/api/users/**

        - id: catalog-service-route
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/api/products/**, /api/categories/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false


jwt:
  secret: "YyN1cDIkUnNlY3VyZV8kM2NyM3QhX2tleV9mb3JfYXV0aGVudGljYXRpb25fMTIzNDU2Nzg5MA=="

app:
  security:
    public-routes:
      - /api/users/login
      - /api/users/register
      - /api/users/refresh